# Generated by Django 5.1.1 on 2024-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_remove_return_return_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_expired',
            field=models.BooleanField(default=False),
        ),
    ]
