# Generated by Django 5.1.1 on 2024-09-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_remove_return_return_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='ecommerce_app.product'),
        ),
    ]
