# Generated by Django 5.1.1 on 2024-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_offer_offer_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
