# Generated by Django 5.1.1 on 2024-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_review_review_product'),
        ('ecommerce_app', '0004_offer_offer_image'),
    ]

    operations = [
    ]
