# Generated by Django 5.1.1 on 2024-09-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_merge_20240924_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_details',
            name='offer_del_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerdata', to='ecommerce_app.offer'),
        ),
    ]
