# Generated by Django 5.1.1 on 2024-09-25 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_alter_product_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_details',
            name='offer_del_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_product_data', to='ecommerce_app.product'),
        ),
    ]
