# Generated by Django 5.1.1 on 2024-09-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_alter_orderdetails_orderdet_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_supplier', models.CharField(max_length=900)),
                ('stock_sku', models.CharField(max_length=150)),
                ('stock_total_order_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Stock_management',
            fields=[
                ('sm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sm_product_name', models.CharField(max_length=300)),
                ('sm_product_code', models.CharField(max_length=10)),
                ('sm_sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('sm_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.brand')),
                ('sm_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce_app.category')),
            ],
            options={
                'db_table': 'Stock_management',
            },
        ),
        migrations.CreateModel(
            name='stock_manage_details',
            fields=[
                ('smd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('smd_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('smd_quantity', models.IntegerField()),
                ('smd_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.color')),
                ('smd_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.size')),
                ('smd_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.stock_management')),
            ],
            options={
                'db_table': 'stock_manage_details',
            },
        ),
        migrations.CreateModel(
            name='Stock_product',
            fields=[
                ('sp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sp_product_name', models.CharField(max_length=300)),
                ('sp_product_code', models.CharField(max_length=10)),
                ('sp_sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('sp_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.brand')),
                ('sp_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce_app.category')),
                ('sp_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.stock')),
            ],
            options={
                'db_table': 'Stock_product',
            },
        ),
        migrations.CreateModel(
            name='stock_details',
            fields=[
                ('sd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sd_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sd_quantity', models.IntegerField()),
                ('sd_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.color')),
                ('sd_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.size')),
                ('sd_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.stock_product')),
            ],
            options={
                'db_table': 'stock_details',
            },
        ),
    ]
