# Generated by Django 5.1.1 on 2024-09-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_stock_stock_management_stock_manage_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_details',
            name='sd_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_details_data', to='ecommerce_app.stock_product'),
        ),
        migrations.AlterField(
            model_name='stock_product',
            name='sp_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_data', to='ecommerce_app.stock'),
        ),
    ]
