# Generated by Django 5.1.1 on 2024-09-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_alter_stock_details_sd_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_manage_details',
            name='smd_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_management_data', to='ecommerce_app.stock_management'),
        ),
    ]
