# Generated by Django 5.1.1 on 2024-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_alter_stock_manage_details_smd_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderDet_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('OutForDelivery', 'OutForDelivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
