# Generated by Django 5.1.1 on 2024-10-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_alter_orderdetails_orderdet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_orders',
            name='assign_orderDet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_order', to='ecommerce_app.orderdetails'),
        ),
    ]
